# Generated by Django 5.0.6 on 2026-07-20 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCohesionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'analyse")),
                ('ice_score', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name="ICE — Indice de Cohésion d'Équipe")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohesion_analyses', to='core.department', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': "Analyse de cohésion d'équipe",
                'verbose_name_plural': "Analyses de cohésion d'équipe",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CohesionCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=500, verbose_name='Critère')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Note (1-5)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='teams.teamcohesionanalysis')),
            ],
            options={
                'verbose_name': 'Note de critère de cohésion',
                'verbose_name_plural': 'Notes de critères de cohésion',
            },
        ),
        migrations.CreateModel(
            name='TeamRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('EXCELLENT', 'Excellente'), ('CORRECT', 'Correcte'), ('DIFFICULT', 'Difficile'), ('TOXIC', 'Toxique')], max_length=10, verbose_name='Qualité')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.department', verbose_name='Équipe')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Relation d'équipe",
                'verbose_name_plural': "Relations d'équipe",
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
