# Generated by Django 5.0.6 on 2026-08-05 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohesioncriterionscore',
            name='achieved_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Réalisé pour ce critère (1-5)'),
        ),
        migrations.AddField(
            model_name='cohesioncriterionscore',
            name='objective_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='OCE — Objectif pour ce critère (1-5)'),
        ),
        migrations.AddField(
            model_name='teamcohesionanalysis',
            name='oce_score',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Moyenne des objectifs par critère — recalculée automatiquement.', max_digits=3, verbose_name="OCE — Objectif de Cohésion d'Équipe (moyenne)"),
        ),
    ]
