# Generated by Django 5.0.6 on 2026-08-10 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_cohesioncriterionscore_achieved_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohesioncriterionscore',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)'),
        ),
    ]
