# Generated by Django 5.0.6 on 2026-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_cohesioncriterionscore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamrelationship',
            options={'ordering': ['id'], 'verbose_name': "Relation d'équipe", 'verbose_name_plural': "Relations d'équipe"},
        ),
    ]
