# Generated by Django 5.0.6 on 2026-09-20 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guesssheet'),
        ('evaluations', '0017_alter_managerialsynthesis_improvement_areas_and_more'),
        ('teams', '0009_cohesion_response_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalSafetyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=list, verbose_name='Notes (12 affirmations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_responses', to='evaluations.evaluationcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_responses', to='core.company')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_responses', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_responses', to='core.department')),
            ],
            options={
                'verbose_name': 'Réponse Psychological Safety',
                'verbose_name_plural': 'Réponses Psychological Safety',
            },
        ),
        migrations.AddConstraint(
            model_name='psychologicalsafetyresponse',
            constraint=models.UniqueConstraint(fields=('respondent', 'campaign'), name='unique_psi_per_respondent_campaign'),
        ),
    ]
