# Generated by Django 5.0.6 on 2026-09-30 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_psychological_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalsafetyresponse',
            name='verdict',
            field=models.CharField(blank=True, choices=[('SAFE', 'Safe'), ('WATCH', 'À surveiller'), ('UNSAFE', 'Non safe')], default='', max_length=10, verbose_name='Appréciation du consultant'),
        ),
        migrations.AddField(
            model_name='psychologicalsafetyresponse',
            name='verdict_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psychologicalsafetyresponse',
            name='verdict_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psi_verdicts_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologicalsafetyresponse',
            name='verdict_comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire du consultant'),
        ),
    ]
