# Generated by Django 5.0.6 on 2026-07-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('LIGHT', 'Clair'), ('DARK', 'Sombre'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=10, verbose_name='Thème'),
        ),
    ]
