# Generated by Django 5.0.6 on 2026-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue'),
        ),
    ]
