# Generated by Django 5.0.6 on 2026-07-28 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(max_length=255, verbose_name="Nom de l'auteur")),
                ('actor_role', models.CharField(blank=True, max_length=20, verbose_name="Rôle de l'auteur")),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Entreprise concernée')),
                ('action', models.CharField(max_length=50, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Événement du journal',
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
