# Generated by Django 5.0.6 on 2026-07-29 11:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('generated_login'), condition=models.Q(('generated_login', ''), _negated=True), name='unique_generated_login_ci'),
        ),
    ]
