# Generated by Django 5.0.6 on 2026-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_unique_generated_login_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_full_body',
            field=models.ImageField(blank=True, help_text="Portrait debout, affiché sur la fiche d'évaluation des managers.", null=True, upload_to='avatars_full/', verbose_name='Photo pleine hauteur'),
        ),
    ]
