# Generated by Django 5.0.6 on 2026-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_avatar_full_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_start_date',
            field=models.DateField(blank=True, help_text="Utilisé pour calculer l'expérience totale.", null=True, verbose_name='Début de carrière'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, help_text="Utilisé pour calculer l'ancienneté dans l'entreprise.", null=True, verbose_name="Date d'entrée dans l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='role_start_date',
            field=models.DateField(blank=True, help_text="Utilisé pour calculer l'ancienneté dans le poste actuel.", null=True, verbose_name='Date de prise de poste actuel'),
        ),
    ]
