# Generated by Django 5.0.6 on 2026-08-10 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_career_start_date_user_hire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Genre')),
                ('contract_type', models.CharField(blank=True, max_length=50, verbose_name='Type de contrat')),
                ('qualifications', models.JSONField(blank=True, default=list, verbose_name='Qualifications')),
                ('previous_positions', models.JSONField(blank=True, default=list, verbose_name='Postes précédents')),
                ('professional_achievements', models.JSONField(blank=True, default=list, verbose_name='Réalisations professionnelles')),
                ('personal_achievements', models.JSONField(blank=True, default=list, verbose_name='Réalisations personnelles')),
                ('vision_aspirations', models.TextField(blank=True, verbose_name='Vision / Aspirations')),
                ('personal_projects', models.TextField(blank=True, verbose_name='Projets personnels')),
                ('professional_role_models', models.JSONField(blank=True, default=list, verbose_name='Modèles professionnels')),
                ('role_models_in_life', models.JSONField(blank=True, default=list, verbose_name='Modèles dans la vie')),
                ('dislikes', models.JSONField(blank=True, default=list, verbose_name="Ce qu'il/elle n'aime pas")),
                ('motivates', models.JSONField(blank=True, default=list, verbose_name='Ce qui le/la motive')),
                ('personality_traits', models.JSONField(blank=True, default=list, verbose_name='Traits de personnalité')),
                ('hobbies', models.JSONField(blank=True, default=list, verbose_name='Loisirs')),
                ('bono_hat', models.CharField(blank=True, max_length=100, verbose_name='Chapeau de Bono')),
                ('brings_to_team', models.JSONField(blank=True, default=list, verbose_name="Apporte à l'équipe")),
                ('brings_to_manager', models.JSONField(blank=True, default=list, verbose_name='Apporte au manager')),
                ('expects_from_team', models.JSONField(blank=True, default=list, verbose_name="Attend de l'équipe")),
                ('expects_from_manager', models.JSONField(blank=True, default=list, verbose_name='Attend du manager')),
                ('dev_priorities', models.JSONField(blank=True, default=list, verbose_name='Priorités de développement')),
                ('dev_professional_perspectives', models.JSONField(blank=True, default=list, verbose_name='Perspectives professionnelles')),
                ('dev_actions_support', models.JSONField(blank=True, default=list, verbose_name='Actions de soutien à la performance')),
                ('dev_risks_obstacles', models.JSONField(blank=True, default=list, verbose_name='Risques / Obstacles / Incertitudes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur')),
            ],
            options={
                'verbose_name': 'Fiche de performance 360°',
                'verbose_name_plural': 'Fiches de performance 360°',
                'ordering': ['id'],
            },
        ),
    ]
