# Generated by Django 5.0.6 on 2026-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_performanceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceprofile',
            name='performance_pct',
            field=models.CharField(blank=True, max_length=20, verbose_name='% de performance (saisi)'),
        ),
        migrations.AddField(
            model_name='performanceprofile',
            name='performer_category',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'Outstanding performer'), ('GOOD', 'Good performer'), ('AVERAGE', 'Average performer'), ('LOW', 'Low performer'), ('VERY_LOW', 'Very low performer')], max_length=20, verbose_name='Catégorie de performance (saisie)'),
        ),
    ]
