# Generated by Django 5.0.6 on 2026-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_performanceprofile_performance_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceprofile',
            name='previous_position_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Dates de début des postes précédents'),
        ),
    ]
