# Generated by Django 5.0.6 on 2026-09-19 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_department_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cohesion_min_respondents',
            field=models.PositiveSmallIntegerField(default=2, help_text="Nombre minimal de collaborateurs ayant répondu pour publier les indices de cohésion d'une direction.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Seuil de publication de la cohésion'),
        ),
    ]
