# Generated by Django 5.0.6 on 2026-09-19 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_cohesion_min_respondents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_name', models.CharField(max_length=120, verbose_name='Nom et prénom du collègue')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Contenu de la fiche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_sheets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_sheets', to='core.company')),
            ],
            options={
                'verbose_name': 'Fiche jeu',
                'verbose_name_plural': 'Fiches jeu',
                'ordering': ['-updated_at'],
            },
        ),
    ]
