# Generated by Django 5.0.6 on 2026-09-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guesssheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrics', models.JSONField(default=list, verbose_name='Rubriques autorisées')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_accesses', to='core.company', verbose_name='Entreprise')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_viewers', to='core.department', verbose_name='Direction consultée')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Directeur lecteur')),
            ],
            options={
                'verbose_name': 'Accès entre directions',
                'verbose_name_plural': 'Accès entre directions',
                'unique_together': {('viewer', 'department')},
            },
        ),
    ]
