# Generated by Django 5.0.6 on 2026-07-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du référentiel')),
                ('type', models.CharField(choices=[('HARD', 'Hard Skills (Aptitudes)'), ('SOFT', 'Soft Skills (Attitudes)')], max_length=10, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_matrices', to='core.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Référentiel de compétences',
                'verbose_name_plural': 'Référentiels de compétences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Compétence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Pondération')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='skills.skillmatrix', verbose_name='Référentiel')),
            ],
            options={
                'verbose_name': 'Item de compétence',
                'verbose_name_plural': 'Items de compétence',
                'ordering': ['matrix', 'order'],
            },
        ),
    ]
