# Generated by Django 5.0.6 on 2026-07-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_language'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatrix',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Département dont les membres utilisent ce référentiel par défaut si aucun référentiel ne correspond exactement à leur poste.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_matrices', to='core.department', verbose_name='Département'),
        ),
    ]
