# Generated by Django 5.0.6 on 2026-07-20 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Ex: 2025-S1, Dec 2025', max_length=32, verbose_name='Période')),
                ('business_objectives_score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Score objectifs business (%)')),
                ('people_objectives_score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Score objectifs people (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur (Manager)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur évalué')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-period'],
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationSkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Note (1-5)')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='evaluations.evaluation')),
                ('skill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='skills.skillitem', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Note de compétence',
                'verbose_name_plural': 'Notes de compétence',
                'unique_together': {('evaluation', 'skill_item')},
            },
        ),
    ]
