# Generated by Django 5.0.6 on 2026-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluationskillscore_objective_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationskillscore',
            name='achievement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Taux de réalisation de l'objectif précédent (%)"),
        ),
    ]
