# Generated by Django 5.0.6 on 2026-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluationskillscore_achievement_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationskillscore',
            name='achievement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="Réalisé par rapport à l'objectif précédent (1-5)"),
        ),
    ]
