# Generated by Django 5.0.6 on 2026-08-08 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_alter_evaluation_business_objectives_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOFT_STRENGTH', 'Force — Soft Skills'), ('SOFT_WEAKNESS', 'Faiblesse — Soft Skills'), ('HARD_STRENGTH', 'Force — Hard Skills'), ('HARD_WEAKNESS', 'Faiblesse — Hard Skills')], max_length=20, verbose_name='Catégorie')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Position (1-5)')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Texte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_notes', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur concerné')),
            ],
            options={
                'verbose_name': 'Note Forces & Faiblesses',
                'verbose_name_plural': 'Notes Forces & Faiblesses',
                'ordering': ['category', 'order'],
                'unique_together': {('user', 'category', 'order')},
            },
        ),
    ]
