# Generated by Django 5.0.6 on 2026-08-08 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_skillnote_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnote',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Indice (1-5)'),
        ),
    ]
