# Generated by Django 5.0.6 on 2026-09-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_performance_objectives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerialSelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COMMUNICATION', 'Communication'), ('ECOUTE', 'Écoute'), ('MOTIVATION', 'Motivation des équipes'), ('DELEGATION', 'Délégation'), ('TEMPS_PRIORITES', 'Gestion du temps et des priorités')], max_length=20, verbose_name='Compétence')),
                ('scores', models.JSONField(blank=True, default=list, help_text='Liste de {order, score, objective_score} — order 1-10, score/objective_score 1-5.', verbose_name='Notes par question')),
                ('ic_score', models.DecimalField(decimal_places=1, default=0, help_text='Moyenne des notes — recalculée automatiquement.', max_digits=3, verbose_name='IC — Indice de Compétence')),
                ('oc_score', models.DecimalField(decimal_places=1, default=0, help_text='Moyenne des objectifs renseignés — recalculée automatiquement.', max_digits=3, verbose_name='OC — Objectif de Compétence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managerial_self_assessments', to='evaluations.evaluationcampaign', verbose_name='Campagne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managerial_self_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Auto-évaluation managériale',
                'verbose_name_plural': 'Auto-évaluations managériales',
                'ordering': ['-campaign__start_date', 'category'],
                'unique_together': {('user', 'campaign', 'category')},
            },
        ),
    ]
