# Generated by Django 5.0.6 on 2026-09-16 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_managerialselfassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonkeyManagementAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(blank=True, default=list, help_text='Liste de {order, score} — order 1-10, score 1-5 (entier).', verbose_name='Notes par affirmation')),
                ('total_score', models.PositiveSmallIntegerField(default=0, help_text='Somme des 10 notes — recalculée automatiquement.', verbose_name='Score total (/50)')),
                ('monkeys', models.JSONField(blank=True, default=list, help_text="Jusqu'à 3 réponses courtes.", verbose_name='Les trois "monkeys" portés à tort')),
                ('why_accepted', models.TextField(blank=True, verbose_name='Pourquoi les avoir acceptés')),
                ('return_to_whom', models.TextField(blank=True, verbose_name='À qui les rendre')),
                ('behavior_to_change', models.TextField(blank=True, verbose_name='Comportement à changer pour ne pas les récupérer')),
                ('next_responsibility', models.TextField(blank=True, verbose_name='Responsabilité supplémentaire à confier cette semaine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monkey_management_assessments', to='evaluations.evaluationcampaign', verbose_name='Campagne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monkey_management_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Auto-diagnostic Monkey Management',
                'verbose_name_plural': 'Auto-diagnostics Monkey Management',
                'ordering': ['-campaign__start_date'],
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
