# Generated by Django 5.0.6 on 2026-09-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_monkeymanagementassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerialselfassessment',
            name='scores',
            field=models.JSONField(blank=True, default=list, help_text='Liste de {order, score, objective_score, comment} — order 1-10, score/objective_score 1-5.', verbose_name='Notes par question'),
        ),
        migrations.CreateModel(
            name='ManagerialSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_skills', models.JSONField(blank=True, default=list, help_text="Jusqu'à 3 réponses courtes.", verbose_name='Compétences clés')),
                ('improvement_areas', models.JSONField(blank=True, default=list, help_text="Jusqu'à 3 réponses courtes.", verbose_name="Axes d'amélioration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managerial_syntheses', to='evaluations.evaluationcampaign', verbose_name='Campagne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managerial_syntheses', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': "Synthèse d'auto-évaluation managériale",
                'verbose_name_plural': "Synthèses d'auto-évaluation managériale",
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
