# Generated by Django 5.0.6 on 2026-09-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_alter_managerialselfassessment_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcampaign',
            name='closed_on',
            field=models.DateField(blank=True, help_text='Jour où le CEO a clôturé la campagne : les saisies faites jusque-là lui restent rattachées.', null=True, verbose_name='Clôturée le'),
        ),
    ]
