# Generated by Django 5.0.6 on 2026-09-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_evaluationcampaign_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerialsynthesis',
            name='improvement_areas',
            field=models.JSONField(blank=True, default=list, help_text="Jusqu'à 10 réponses courtes.", verbose_name="Axes d'amélioration"),
        ),
        migrations.AlterField(
            model_name='managerialsynthesis',
            name='key_skills',
            field=models.JSONField(blank=True, default=list, help_text="Jusqu'à 10 réponses courtes.", verbose_name='Compétences clés'),
        ),
    ]
