# Generated by Django 5.0.6 on 2026-09-20 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guesssheet'),
        ('evaluations', '0017_alter_managerialsynthesis_improvement_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FEEDBACK', '360° Feedback'), ('FORWARD', '360° Forward')], max_length=10)),
                ('relation', models.CharField(choices=[('SELF', 'Soi-même'), ('MANAGER', 'Manager'), ('REPORT', 'Collaborateur direct'), ('PEER', 'Pair')], max_length=10)),
                ('scores', models.JSONField(blank=True, default=list)),
                ('text_a', models.TextField(blank=True)),
                ('text_b', models.TextField(blank=True)),
                ('text_c', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_360', to='evaluations.evaluationcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_360', to='core.company')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis 360°',
                'verbose_name_plural': 'Avis 360°',
            },
        ),
        migrations.AddConstraint(
            model_name='feedback360',
            constraint=models.UniqueConstraint(fields=('author', 'subject', 'campaign', 'kind'), name='unique_feedback360_per_author_subject'),
        ),
    ]
