# Generated by Django 5.0.6 on 2026-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HARD_SKILLS', 'Hard Skills'), ('SOFT_SKILLS', 'Soft Skills')], max_length=20, verbose_name='Catégorie')),
                ('priority', models.CharField(max_length=255, verbose_name='Priorité de développement')),
                ('objective', models.TextField(verbose_name='Action à mener')),
                ('baseline', models.CharField(blank=True, max_length=50, verbose_name='Score de départ')),
                ('target', models.CharField(blank=True, max_length=50, verbose_name='Score cible')),
                ('cost', models.CharField(blank=True, max_length=100, verbose_name='Coût')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='TODO', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'action",
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
