# Generated by Django 5.0.6 on 2026-07-20 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actionplans', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to=settings.AUTH_USER_MODEL, verbose_name='Manager responsable'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si le plan concerne toute l'équipe.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_action_plans', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur concerné'),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='core.department', verbose_name='Équipe'),
        ),
    ]
