# Generated by Django 5.0.6 on 2026-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionplans', '0003_actionplan_eval_note_actionplan_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
