# Generated by Django 5.0.6 on 2026-08-14 16:12

from django.conf import settings
from django.db import migrations, models


def split_order_into_priority_and_action(apps, schema_editor):
    """Les lignes existantes de la grille portaient une action par priorité :
    `order` (1-3) devient le numéro de priorité, et l'action prend le rang 1."""
    ActionPlan = apps.get_model("actionplans", "ActionPlan")
    ActionPlan.objects.filter(order__isnull=False).update(
        priority_order=models.F("order"), order=1
    )


def merge_priority_into_order(apps, schema_editor):
    """Retour arrière : seule la première action de chaque priorité tient dans
    l'ancien schéma (une ligne par priorité), les suivantes sont supprimées."""
    ActionPlan = apps.get_model("actionplans", "ActionPlan")
    ActionPlan.objects.filter(order__isnull=False).exclude(order=1).delete()
    ActionPlan.objects.filter(order__isnull=False).update(order=models.F("priority_order"))


class Migration(migrations.Migration):

    dependencies = [
        ('actionplans', '0004_actionplan_start_date_alter_actionplan_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='priority_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numéro de la priorité de développement dans la grille du plan de développement (3 par catégorie).', null=True, verbose_name='Priorité (1-3)'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Renseigné uniquement pour la grille du plan de développement d'un manager : une priorité porte autant d'actions que nécessaire, numérotées à partir de 1.", null=True, verbose_name="Position de l'action dans la priorité"),
        ),
        migrations.RunPython(split_order_into_priority_and_action, merge_priority_into_order),
        migrations.AlterUniqueTogether(
            name='actionplan',
            unique_together={('target_user', 'category', 'priority_order', 'order')},
        ),
    ]
